version: "3.8"

services:
  frontend:
    build:
      context: ./geojson-frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./geojson-backend
      target: production
    ports:
      - "3044:3044"
