version: '3.8'

services:
  frontend:
    build:
      context: ./geojson-frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./geojson-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./geojson-backend
      target: development
    ports:
      - "3044:3044"
    volumes:
      - ./geojson-backend:/app
      - /app/node_modules
